version: '3.8'

services:
  socialnet-chat-tests:
    container_name: socialnet-chat-tests
    build:
      context: ./
      dockerfile: ./apps/socialnet-chat/test.Dockerfile
    environment:
      PORT: 3000
    ports:
      - '3001:3000'
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules

  socialnet-api-tests:
    container_name: socialnet-api-tests
    build:
      context: ./
      dockerfile: ./services/socialnet-api/test.Dockerfile
    environment:
      PORT: 4000
    ports:
      - '4001:4000'
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
