version: '3.8'

services:
  socialnet-chat-tests:
    container_name: socialnet-chat
    build:
      context: ./
      dockerfile: ./apps/socialnet-chat/test.Dockerfile
    environment:
      PORT: 3000
    depends_on:
      - socialnet-api
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules

  socialnet-api-tests:
    container_name: socialnet-api
    build:
      context: ./
      dockerfile: ./services/socialnet-api/test.Dockerfile
    environment:
      PORT: 4000
    ports:
      - '4000:4000'
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
